spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineMusic
    username: postgres
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  access-token:
    lifetime: 5
  secret-key: Snd0VG9rZW5Qcm9qZWN0T25saW5lTXVzaWNBdXRoZW50aWNhdGlvbjI1NmJpdA==

logging:
  level:
    org.springframework.security: TRACE
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, beans
